const babelParser = require('@babel/eslint-parser');
const eslintPluginEmotion = require('@emotion/eslint-plugin');
const eslintPluginImport = require('eslint-plugin-import');
const eslintPluginJsxA11y = require('eslint-plugin-jsx-a11y');
const eslintPluginPrettier = require('eslint-plugin-prettier');
const eslintPluginReact = require('eslint-plugin-react');
const eslintPluginReactHooks = require('eslint-plugin-react-hooks');
const sonarjs = require('eslint-plugin-sonarjs');

module.exports = [
    {
        files: ['**/*.{js,jsx,ts,tsx}'],
        languageOptions: {
            parser: babelParser,
            parserOptions: {
                requireConfigFile: false,
                babelOptions: {
                    presets: ['@babel/preset-react'],
                },
            },
            sourceType: 'module',
            globals: {
                __DEV__: 'readonly',
            },
        },
        plugins: {
            import: eslintPluginImport,
            react: eslintPluginReact,
            'react-hooks': eslintPluginReactHooks,
            prettier: eslintPluginPrettier,
            '@emotion': eslintPluginEmotion,
            'jsx-a11y': eslintPluginJsxA11y,
            sonarjs,
        },
        settings: {
            react: {
                version: 'detect',
            },
            'import/parsers': {
                '@typescript-eslint/parser': ['.ts', '.tsx'],
            },
            'import/resolver': {
                'babel-module': {
                    cwd: __dirname,
                    extensions: ['.js', '.jsx', '.ts', '.tsx'],
                },
            },
        },
        rules: {
            ...sonarjs.configs.recommended.rules,
            'import/extensions': [
                'error',
                'ignorePackages',
                {
                    js: 'never',
                    jsx: 'never',
                    ts: 'never',
                    tsx: 'never',
                },
            ],
            'import/order': [
                'error',
                {
                    groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
                    'newlines-between': 'never',
                    alphabetize: { order: 'asc', caseInsensitive: true },
                    pathGroups: [
                        {
                            pattern: 'react',
                            group: 'external',
                            position: 'before',
                        },
                    ],
                    pathGroupsExcludedImportTypes: ['react'],
                },
            ],
            'import/no-duplicates': 'error',
            'import/no-unresolved': 'error',
            'import/named': 'error',
            'import/default': 'error',
            'import/namespace': 'error',
            'import/no-cycle': 'warn',
            'import/no-useless-path-segments': 'error',
            'import/first': 'error',
            'import/prefer-default-export': 'off',
            'prettier/prettier': ['error'],
            'no-alert': 'warn',
            'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-new': 'warn',
            'no-loop-func': 'warn',
            'no-restricted-globals': 'error',
            'class-methods-use-this': 'off',
            'function-paren-newline': 'off',
            'space-before-function-paren': 'off',
            'object-curly-newline': 'off',
            'no-underscore-dangle': 'off',
            'no-self-compare': 'error',
            'arrow-parens': 'off',
            'arrow-body-style': 'off',
            'no-plusplus': 'off',
            'no-restricted-exports': 'off',
            'no-param-reassign': ['error', { props: false }],
            'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
            'max-len': [
                'error',
                120,
                4,
                {
                    ignoreUrls: true,
                    ignoreComments: false,
                    ignoreRegExpLiterals: true,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                    ignorePattern: '<path([sS]*?)/>',
                },
            ],
            'comma-dangle': [
                'error',
                {
                    arrays: 'always-multiline',
                    objects: 'always-multiline',
                    imports: 'only-multiline',
                    exports: 'only-multiline',
                    functions: 'only-multiline',
                },
            ],
            'prefer-destructuring': [
                'error',
                {
                    VariableDeclarator: {
                        array: false,
                        object: true,
                    },
                    AssignmentExpression: {
                        array: false,
                        object: false,
                    },
                },
                {
                    enforceForRenamedProperties: false,
                },
            ],
            'implicit-arrow-linebreak': 'off',
            'wrap-iife': ['error', 'any'],
            camelcase: 'off',
            '@emotion/pkg-renaming': 'error',
            'react/no-danger': 'warn',
            'react/require-default-props': 'off',
            'react/function-component-definition': [
                'error',
                {
                    namedComponents: ['arrow-function', 'function-declaration'],
                    unnamedComponents: 'arrow-function',
                },
            ],
            'react/jsx-wrap-multilines': [
                'error',
                {
                    declaration: 'parens-new-line',
                    assignment: 'parens-new-line',
                    return: 'parens-new-line',
                    arrow: 'parens-new-line',
                    condition: 'parens-new-line',
                    logical: 'parens-new-line',
                    prop: 'ignore',
                },
            ],
            'react/jsx-indent': ['error', 4],
            'react/jsx-indent-props': ['error', 4],
            'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx', '.tsx', '.mdx'] }],
            'react/forbid-prop-types': 'off',
            'react/jsx-closing-tag-location': 'error',
            'react/jsx-one-expression-per-line': 'off',
            'react/no-unused-prop-types': 'warn',
            'react/static-property-placement': 'off',
            'react/destructuring-assignment': 'off',
            'react/jsx-no-useless-fragment': 'warn',
            'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
            'react/jsx-boolean-value': ['error', 'never'],
            'react/no-array-index-key': 'warn',
            'react/jsx-key': ['error', { checkFragmentShorthand: true }],
            'react/jsx-no-duplicate-props': 'error',
            'react/jsx-pascal-case': 'error',
            'react/self-closing-comp': 'error',
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',
            'jsx-a11y/href-no-hash': 'off',
            'jsx-a11y/accessible-emoji': 'off',
            'jsx-a11y/alt-text': 'error',
            'jsx-a11y/anchor-has-content': 'error',
            'jsx-a11y/anchor-is-valid': ['error', { components: ['Link'], specialLink: ['to'] }],
            'jsx-a11y/aria-props': 'error',
            'jsx-a11y/aria-proptypes': 'error',
            'jsx-a11y/aria-role': ['error', { ignoreNonDOM: true }],
            'jsx-a11y/aria-unsupported-elements': 'error',
            'jsx-a11y/click-events-have-key-events': 'warn',
            'jsx-a11y/heading-has-content': 'error',
            'jsx-a11y/html-has-lang': 'error',
            'jsx-a11y/iframe-has-title': 'error',
            'jsx-a11y/img-redundant-alt': 'error',
            'jsx-a11y/interactive-supports-focus': 'warn',
            'jsx-a11y/label-has-associated-control': ['error', { assert: 'either' }],
            'jsx-a11y/mouse-events-have-key-events': 'warn',
            'jsx-a11y/no-access-key': 'error',
            'jsx-a11y/no-autofocus': 'off',
            'jsx-a11y/no-distracting-elements': 'error',
            'jsx-a11y/no-interactive-element-to-noninteractive-role': 'warn',
            'jsx-a11y/no-noninteractive-element-interactions': 'warn',
            'jsx-a11y/no-noninteractive-element-to-interactive-role': 'warn',
            'jsx-a11y/no-noninteractive-tabindex': 'warn',
            'jsx-a11y/no-redundant-roles': 'error',
            'jsx-a11y/no-static-element-interactions': 'warn',
            'jsx-a11y/role-has-required-aria-props': 'error',
            'jsx-a11y/role-supports-aria-props': 'error',
            'jsx-a11y/tabindex-no-positive': 'warn',
            'react/jsx-props-no-spreading': 'off',
        },
    },
];
