name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install project
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint:all

      - name: Zip artifact for deployment
        run: zip -r build.zip build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
